/*
  # Add Category Column to Items Table

  This migration adds a category column to store the AI-generated tag for each item,
  enabling users to filter items by category.

  ## Changes Made

  1. New Column on `items` table:
     - `category` (text, nullable) - Stores the item category/tag generated by AI
       Examples: 'couch', 'chair', 'table', 'bookshelf', 'lamp', 'tv', etc.

  2. Index Added:
     - `items_category_idx` - Index on category column for efficient filtering

  ## Notes
  - Column is nullable to support existing items that don't have a category
  - New items will have category populated from the AI-generated tag
*/

-- Add category column to items table
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'items' AND column_name = 'category'
  ) THEN
    ALTER TABLE items ADD COLUMN category text;
  END IF;
END $$;

-- Create index for category filtering
CREATE INDEX IF NOT EXISTS items_category_idx ON items(category);